### ISSUE TITLE
Compiling "mediascan_unix.c" on Solaris 11 Express

### ISSUE THREAD

**Issue by ghost** [andygrundman/libmediascan#1]
Compiling "mediascan_unix.c" resulted in a problem concerned with the d_type/DT_DIR issue on some platforms (line 114 in "mediascan_unix.c")

The problem could be solved by adding the following line to the file:

in case of  (line 114):
if (dp->d_type == DT_DIR) {
I put: 
stat(dp->d_name, &t); 
if ((t.st_mode & S_IFMT) == S_IFDIR) {

I also had to add "struct stat t;" to function "recurse_dir"

Maybe this helps to get libmediascan running on Solaris/Openindiana

**Comment by fsbruva** [comment]
Closed via #6. Please test to make sure it works for your platform.
